# Generated by Django 4.2 on 2023-05-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prak11', '0003_alter_classification_id_alter_group_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prak11.user'),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
